"""
Tests for the --vmd-bin path: indexer runs dump_help.tcl in headless
VMD and ingests the resulting plaintext into the vmd_ref scope.

We never have a real VMD on test machines, so the test installs a
small shell-script "stub" that mimics:

    vmd -dispdev text -e <script>

The stub honors $VMD_AI_HELP_OUT (the path the indexer tells dump_help
to write to) and writes a canned help corpus. The point of these tests
is to verify the indexer's subprocess plumbing — that it sets the env
var, locates the script, captures the output, and pipes it into the
plaintext chunker.

Auto-detection paths and missing-binary paths are covered separately.
"""
from __future__ import annotations

import json
import os
import stat
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUNTIME_DIR = ROOT / "runtime"
if str(RUNTIME_DIR) not in sys.path:
    sys.path.insert(0, str(RUNTIME_DIR))

from vmd_ai_runtime.docs_search import DocsSearch  # noqa: E402
from vmd_ai_runtime.scripts.build_docs_index import (  # noqa: E402
    _classify_extension,
    _detect_user_guide_html,
    _detect_vmd_binary,
    _detect_vmd_install,
    cli as indexer_cli,
)


# ----------------------------------------------------------------------
# Stub-binary builder
# ----------------------------------------------------------------------

STUB_HELP_TEXT = """# VMD AI help dump v1
# generated by stub vmd

=== mol ===
Usage: mol <subcommand> [args...]
Subcommands include: load, new, delete, representation, color, addrep,
delrep, selection, material.
Use `mol load pdb 1ubq.pdb` to load a structure by PDB ID file.

=== atomselect ===
Create a selection object: atomselect <molid> "<selection_string>".
Returns a Tcl proc handle. Always call $sel delete when done.

=== render ===
Render the current viewport to disk. Two backends:
- render snapshot <file>           # OpenGL framebuffer, fast TGA
- render TachyonInternal <file>    # ray-traced, slower

=== measure ===
Geometric measurements over selections:
- measure rmsd <selA> <selB>
- measure hbonds <cutoff> <angle> <selA> [<selB>]
- measure contacts <cutoff> <selA> <selB>     # cross-molecule friendly

# documented=4 missing=0
"""


def _make_stub_vmd(work_dir: Path, *, exit_code: int = 0,
                  emit_output: bool = True) -> Path:
    """Write an executable shell script that pretends to be `vmd`.

    The real call is `vmd -dispdev text -e <script.tcl>`. The stub
    ignores its args, reads $VMD_AI_HELP_OUT, and writes STUB_HELP_TEXT
    there (or skips writing if `emit_output=False`, to test the
    no-output failure mode).
    """
    stub_path = work_dir / "vmd_stub.sh"
    out_branch = (
        f'cat > "$VMD_AI_HELP_OUT" <<\'EOF\'\n{STUB_HELP_TEXT}EOF\n'
        if emit_output else ""
    )
    stub_path.write_text(
        "#!/usr/bin/env bash\n"
        "# stub vmd binary for tests\n"
        f"{out_branch}"
        f"exit {exit_code}\n"
    )
    stub_path.chmod(stub_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    return stub_path


# ----------------------------------------------------------------------
# Subprocess plumbing
# ----------------------------------------------------------------------

class VmdBinIndexerTests(unittest.TestCase):

    def test_vmd_bin_help_dump_is_indexed(self):
        with tempfile.TemporaryDirectory() as tmp:
            tmp_p = Path(tmp)
            stub = _make_stub_vmd(tmp_p)
            out_dir = tmp_p / "idx"

            rc = indexer_cli([
                "--rebuild",
                "--out", str(out_dir),
                "--skills", "/dev/null",
                "--vmd-bin", str(stub),
            ])
            self.assertEqual(rc, 0)

            ds = DocsSearch(index_dir=str(out_dir))
            self.assertTrue(ds.is_available)

            # Searching for a topic only present in the stub help text
            # should retrieve it. If this fails the indexer didn't
            # actually invoke the stub or didn't pipe its output in.
            res = ds.search("how do I render TachyonInternal", k=3)
            self.assertTrue(res["ok"])
            joined = " ".join(r["text"] for r in res["results"])
            self.assertIn("TachyonInternal", joined)

    def test_vmd_bin_failure_does_not_break_index(self):
        """If the vmd binary fails, the indexer falls back to the other
        sources without crashing. We pass --user-guide so the index is
        non-empty, and verify the overall build still succeeds."""
        with tempfile.TemporaryDirectory() as tmp:
            tmp_p = Path(tmp)
            failing = _make_stub_vmd(tmp_p, exit_code=1, emit_output=False)
            out_dir = tmp_p / "idx"

            rc = indexer_cli([
                "--rebuild",
                "--out", str(out_dir),
                "--user-guide",
                str(ROOT / "tests" / "fixtures" / "docs" / "user_guide_html"),
                "--skills", "/dev/null",
                "--vmd-bin", str(failing),
            ])
            # The fallback path should still produce a usable index.
            self.assertEqual(rc, 0)
            ds = DocsSearch(index_dir=str(out_dir))
            self.assertTrue(ds.is_available)

    def test_vmd_bin_no_output_file_handled(self):
        """If the binary exits 0 but writes nothing, we shouldn't claim
        the help dump is in the index."""
        with tempfile.TemporaryDirectory() as tmp:
            tmp_p = Path(tmp)
            silent = _make_stub_vmd(tmp_p, exit_code=0, emit_output=False)
            out_dir = tmp_p / "idx"

            rc = indexer_cli([
                "--rebuild",
                "--out", str(out_dir),
                "--user-guide",
                str(ROOT / "tests" / "fixtures" / "docs" / "user_guide_html"),
                "--skills", "/dev/null",
                "--vmd-bin", str(silent),
            ])
            self.assertEqual(rc, 0)
            # Manifest's vmd_ref count should be 0 — only user_guide
            # made it in.
            manifest = json.loads(
                (out_dir / "manifest.json").read_text()
            )
            self.assertNotIn("vmd_ref", manifest["scope_counts"])
            self.assertIn("user_guide", manifest["scope_counts"])

    def test_vmd_bin_missing_executable(self):
        """Pointing at a non-existent binary should not raise."""
        with tempfile.TemporaryDirectory() as tmp:
            tmp_p = Path(tmp)
            bogus = tmp_p / "definitely_not_a_binary"
            out_dir = tmp_p / "idx"

            rc = indexer_cli([
                "--rebuild",
                "--out", str(out_dir),
                "--user-guide",
                str(ROOT / "tests" / "fixtures" / "docs" / "user_guide_html"),
                "--skills", "/dev/null",
                "--vmd-bin", str(bogus),
            ])
            # User-guide source still produces an index.
            self.assertEqual(rc, 0)


# ----------------------------------------------------------------------
# File classification
# ----------------------------------------------------------------------

class ExtensionClassificationTests(unittest.TestCase):

    def test_md_classified_as_markdown(self):
        self.assertEqual(_classify_extension(Path("/x/foo.md")), "markdown")

    def test_html_and_htm_classified(self):
        self.assertEqual(_classify_extension(Path("/x/a.html")), "html")
        self.assertEqual(_classify_extension(Path("/x/a.htm")), "html")

    def test_txt_classified_as_plaintext(self):
        self.assertEqual(_classify_extension(Path("/x/r.txt")), "plaintext_ref")

    def test_unknown_extension_returns_none(self):
        self.assertIsNone(_classify_extension(Path("/x/r.png")))
        self.assertIsNone(_classify_extension(Path("/x/r")))


# ----------------------------------------------------------------------
# VMD install auto-detection
# ----------------------------------------------------------------------

class AutoDetectionTests(unittest.TestCase):

    def test_detect_vmd_install_returns_none_when_nothing_present(self):
        """With no VMD installed and no env vars, detection returns None
        rather than raising. The CI machine running these tests has no
        VMD, so this is the realistic path."""
        old = os.environ.pop("VMD_INSTALL_DIR", None)
        old2 = os.environ.pop("VMDDIR", None)
        try:
            # Detection might find an OS-provided VMD on dev machines —
            # if that happens, just verify the call returns either None
            # or a real existing directory.
            result = _detect_vmd_install()
            if result is not None:
                self.assertTrue(result.is_dir())
        finally:
            if old is not None:
                os.environ["VMD_INSTALL_DIR"] = old
            if old2 is not None:
                os.environ["VMDDIR"] = old2

    def test_detect_vmd_install_honors_env_var(self):
        """A user-set VMD_INSTALL_DIR wins over heuristic search."""
        with tempfile.TemporaryDirectory() as tmp:
            os.environ["VMD_INSTALL_DIR"] = tmp
            try:
                result = _detect_vmd_install()
                self.assertEqual(result, Path(tmp))
            finally:
                os.environ.pop("VMD_INSTALL_DIR", None)

    def test_detect_user_guide_html_finds_html_files(self):
        """Given an install dir that contains doc/ug/<x.html>, the
        helper should return the doc/ug path."""
        with tempfile.TemporaryDirectory() as tmp:
            install = Path(tmp)
            ug_dir = install / "doc" / "ug"
            ug_dir.mkdir(parents=True)
            (ug_dir / "chap1.html").write_text("<h1>X</h1>", encoding="utf-8")
            self.assertEqual(_detect_user_guide_html(install), ug_dir)

    def test_detect_user_guide_html_returns_none_when_empty(self):
        with tempfile.TemporaryDirectory() as tmp:
            install = Path(tmp)
            (install / "doc").mkdir()
            self.assertIsNone(_detect_user_guide_html(install))

    def test_detect_vmd_binary_returns_none_for_empty_install(self):
        """Without a vmd in PATH and an empty install dir, returns None."""
        with tempfile.TemporaryDirectory() as tmp:
            install = Path(tmp)
            result = _detect_vmd_binary(install)
            # We can't guarantee `which vmd` returns nothing in every
            # dev environment, so this test is permissive: either None
            # (clean env) or a real existing executable (dev with VMD).
            if result is not None:
                self.assertTrue(result.is_file())
                self.assertTrue(os.access(result, os.X_OK))


if __name__ == "__main__":
    unittest.main()
