#
# dump_help.tcl — emit text dumps of every documented VMD command.
#
# Run as:  vmd -dispdev text -e dump_help.tcl
# Optional env: VMD_AI_HELP_OUT (output path; default = ./vmd_help.txt)
#
# Output is plaintext, one section per command, separated by blank lines:
#
#     === <command> ===
#     <help text...>
#
# The indexer's chunk_plaintext_ref consumes this directly: each blank-
# line block becomes one chunk in the vmd_ref scope.
#

# Curated list of top-level VMD commands worth documenting. Iterating
# `info commands` would also pull in every Tcl built-in (`set`, `if`,
# `proc` ...) which dilutes the index without adding anything specific
# to molecular visualization.
set ::vmdai_commands {
    animate atomselect axes color colorinfo display draw graphics
    imd label light lights material measure mol molinfo mouse
    parallel pbc play psfgen render rotate rotmat scale segment
    show topo trans translate vmdcon vmdinfo wait

    pdbload psfload xyzload dcdload mmcifload bondsearch
    sasa rmsd rmsf hbonds contacts gofr

    user_glyph
}

set out_path [expr {[info exists ::env(VMD_AI_HELP_OUT)] ? $::env(VMD_AI_HELP_OUT) : "vmd_help.txt"}]
set fp [open $out_path w]

# Write a header so consumers can detect the file format and version.
puts $fp "# VMD AI help dump v1"
puts $fp "# generated by dump_help.tcl"
puts $fp ""

set documented 0
set missing 0
foreach cmd $::vmdai_commands {
    set body ""
    # `help <cmd>` is the canonical interactive help entry point in VMD.
    # Some commands have it; some print to stdout; some return text.
    # We try `help`, then fall back to `<cmd> help` (the convention used
    # by `mol`, `display`, etc. which take `help` as a subcommand).
    if {[catch {help $cmd} body] || $body eq ""} {
        if {[catch {$cmd help} body] || $body eq ""} {
            set body ""
        }
    }
    if {$body eq ""} {
        incr missing
        continue
    }
    puts $fp "=== $cmd ==="
    puts $fp $body
    puts $fp ""
    incr documented
}

puts $fp "# documented=$documented missing=$missing"
close $fp
puts "[VMD AI] dumped help for $documented commands ($missing missing) -> $out_path"

# Exit cleanly so `-e` mode doesn't drop us into the Tcl REPL.
quit
