#!/usr/bin/env python3
"""
rag_wiki_ab_extract.py — turn the 2×2 harness's per-(prompt, arm) JSON
files into replayable Tcl scripts you can run in real VMD to actually
see the figures.

The 2×2 harness (`scripts/rag_wiki_ab.py`) stubs VMD by design, so it
captures every Tcl command the model emitted but never runs them. This
script walks an out-dir of `<prompt_id>.<arm>.json` files and writes
one `<prompt_id>.<arm>.tcl` next to each, plus a `replay_all.sh`
convenience driver.

Workflow:

    1. python scripts/rag_wiki_ab.py --arms none,wiki --only pore_hydrophobicity
    2. python scripts/rag_wiki_ab_extract.py rag_wiki_results/
    3. cd rag_wiki_results/replay && vmd -e pore_hydrophobicity.wiki.tcl
       # snapshots land under ./snapshots/

Caveat: prompts that don't make the model load a structure (e.g.
conceptual "what's the difference between NewCartoon and Tube?") will
produce Tcl with no `mol new`, so the rendered snapshots will be empty.
For figures, use prompts that pin a PDB ID.
"""
from __future__ import annotations

import argparse
import sys
import json
from pathlib import Path
from typing import List

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

# Reuse the existing per-arm Tcl renderer. The signature it wants is:
#   _render_arm_script(prompt: str, arm_dict: Dict, label: str) -> str
# and arm_dict needs `tool_calls`, `elapsed_s`, `error`, `name`.
from rag_ab_extract import _render_arm_script  # noqa: E402


def _trial_to_arm_dict(trial: dict, label: str) -> dict:
    """Adapt the 2×2 harness JSON shape into what _render_arm_script wants."""
    return {
        "name": label,
        "tool_calls": trial.get("tool_calls") or [],
        "elapsed_s": float(trial.get("elapsed_s") or 0.0),
        "error": trial.get("error"),
    }


def _discover_trials(in_dir: Path) -> List[Path]:
    """Find <prompt_id>.<arm>.json files in `in_dir`, ignoring scorecard/summary."""
    trials: List[Path] = []
    for p in sorted(in_dir.glob("*.json")):
        if p.name in {"summary.json", "scorecard.json"}:
            continue
        # 2x2 layout uses two dots in the stem: "<prompt>.<arm>.json"
        if p.stem.count(".") != 1:
            continue
        trials.append(p)
    return trials


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    ap.add_argument(
        "in_dir",
        help="Directory containing <prompt_id>.<arm>.json files "
             "(the --out-dir you gave rag_wiki_ab.py).",
    )
    ap.add_argument(
        "--out-subdir", default="replay",
        help="Subdirectory of in_dir to write .tcl files into "
             "(default: replay/).",
    )
    args = ap.parse_args(argv)

    in_dir = Path(args.in_dir).expanduser().resolve()
    if not in_dir.is_dir():
        print(f"[extract] not a directory: {in_dir}", file=sys.stderr)
        return 2

    out_dir = in_dir / args.out_subdir
    out_dir.mkdir(parents=True, exist_ok=True)

    trials = _discover_trials(in_dir)
    if not trials:
        print(f"[extract] no <prompt>.<arm>.json files in {in_dir}",
              file=sys.stderr)
        return 1

    written: List[Path] = []
    for jp in trials:
        try:
            trial = json.loads(jp.read_text(encoding="utf-8"))
        except Exception as exc:
            print(f"[extract] skip {jp.name}: {exc}", file=sys.stderr)
            continue
        prompt_id = trial.get("prompt_id") or jp.stem.split(".", 1)[0]
        arm = trial.get("arm") or jp.stem.rsplit(".", 1)[-1]
        prompt = trial.get("prompt") or ""
        label = f"{prompt_id}.{arm}"

        tcl = _render_arm_script(prompt, _trial_to_arm_dict(trial, label),
                                 label)
        out_file = out_dir / f"{label}.tcl"
        out_file.write_text(tcl, encoding="utf-8")
        n_cmd = sum(1 for c in trial.get("tool_calls") or []
                    if c.get("tool_name") == "run_vmd_command")
        n_snap = sum(1 for c in trial.get("tool_calls") or []
                     if c.get("tool_name") == "capture_vmd_snapshot")
        print(f"[extract] {out_file.relative_to(in_dir)}  "
              f"({n_cmd} vmd commands, {n_snap} snapshots)")
        written.append(out_file)

    # Convenience driver: run every script under a dedicated snapshots dir.
    driver = out_dir / "replay_all.sh"
    driver_lines = [
        "#!/usr/bin/env bash",
        "# Generated by rag_wiki_ab_extract.py. Replays each .tcl in this",
        "# directory in headless VMD. Snapshots land in ./snapshots_<label>/.",
        "set -euo pipefail",
        "cd \"$(dirname \"$0\")\"",
        "",
    ]
    for f in written:
        label = f.stem
        driver_lines.append(f"echo '=== {label} ==='")
        driver_lines.append(f"mkdir -p snapshots_{label}")
        # `display update` + per-script render preamble already in the Tcl.
        # We point ./snapshots/ at a label-specific dir per replay so arms
        # don't overwrite each other.
        driver_lines.append(
            f"(rm -rf snapshots && ln -s snapshots_{label} snapshots && "
            f"vmd -dispdev text -e {f.name})"
        )
        driver_lines.append("")
    driver.write_text("\n".join(driver_lines), encoding="utf-8")
    driver.chmod(0o755)
    print(f"\n[extract] wrote convenience driver: {driver.relative_to(in_dir)}")
    print("[extract] replay any single arm with:")
    print(f"    cd {out_dir} && vmd -e <prompt>.<arm>.tcl")
    print("[extract] or replay everything headlessly:")
    print(f"    bash {driver}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
